name: attendence
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  intl: ^0.17.0

  google_maps_flutter: ^2.5.0

  dio: ^5.4.0

  http: ^1.1.0

  retrofit: ^4.1.0

  flutter_bloc: ^8.1.4

  fluttertoast: ^8.2.4

  json_annotation: ^4.8.1

  built_value: ^8.9.0

  provider: ^6.1.1

  shared_preferences: ^2.2.2

  flutter_local_notifications: ^9.3.2

  file: ^6.1.4

  location: ^5.0.3

  url_launcher: ^6.1.14

  timeline_tile: ^2.0.0

  permission_handler: ^10.3.0

  flutter_background_service: ^5.0.5

  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/image/logo.png"

flutter_geofence:

  flutter_lints: ^2.0.0

  retrofit_generator: ^8.1.0

  build_runner: ^2.4.8

  json_serializable: ^6.7.1

  built_value_generator: ^8.9.0


flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
        - asset: assets/fonts/montserrat_semibold.ttf
        - asset: assets/fonts/montserrat_regular.ttf

  assets:
    - assets/image/
    - assets/fonts/
    - assets/image/bg.jpg
    - assets/image/ahs_bk.png
    - assets/image/ahsfull.png
    - assets/image/icon_black.png
    - assets/image/icon_bell.png
    - assets/image/icon_profile.png
    - assets/image/icon_profile1.png
    - assets/image/user_attendence48.png
    - assets/image/user_profile48.png
    - assets/image/icon_doc_gold.png
    - assets/image/icon_doc_grey.png
    - assets/image/icon_user_gold.png
    - assets/image/icon_user_grey.png
    - assets/image/user_location.png
    - assets/image/user_request.png
    - assets/image/logo.png